### ISSUE TITLE
wbopendata issue

### ISSUE THREAD

**Issue by florinapirlea** [jpazvd/wbopendata#4] opened 2019-03-20 22:12 UTC
A staff member has some trouble with the wbopendata command.

![image](https://user-images.githubusercontent.com/25537857/54722631-47b97180-4b3b-11e9-9ecd-e4efc2bb9244.png)

![image](https://user-images.githubusercontent.com/25537857/54722426-da0d4580-4b3a-11e9-930b-485b9f9c2043.png)

![image](https://user-images.githubusercontent.com/25537857/54722474-02953f80-4b3b-11e9-93b3-5f9d1534e566.png)

Her command works on my computer.

Should I ask for more information?

**Comment by jpazvd** [comment] 2019-03-21 03:51
Many thanks Florina and Pierela,

This issue has been identified, and the problem is with on the buidling of the v 15.1 WBOPENDATA SSC distribution package.

A request has already been made to the manager of SSC to make sure that the WBOPENDATA package v15.1 is parsing all required subroutines, such as the _countrymetadata. 

`net describe wbopendata, from(http://fmwww.bc.edu/RePEc/bocode/w`

WBOPENDATA v.15.1 has a significantly higher number of subroutines, which by mistake are currently **not** being transferred through the SSC repository. 

[https://github.com/jpazvd/wbopendata/blob/master/wbopendata.pkg](https://github.com/jpazvd/wbopendata/blob/master/wbopendata.pkg)

The immediate solution is to download WBOPENDATA v. 15.1 directly form its GitHub  REPO, by using the  following command lines in Stata:

```
net install github, from("https://haghish.github.io/github/")
github install jpazvd/wbopendata, force
```

All the very best,

JP

**Closed by jpazvd** 2019-03-21 03:51 UTC
Labels: bug
